language: python
python:
    - 3.7
    - 3.8
    
arch:
    - amd64
    - ppc64le
    
services:
    - postgresql
    - mysql
env:
    - DJANGO=1.11 DATABASE_ENGINE=sqlite
    - DJANGO=1.11 DATABASE_ENGINE=postgres
    - DJANGO=1.11 DATABASE_ENGINE=mysql
    - DJANGO=2.2 DATABASE_ENGINE=sqlite
    - DJANGO=2.2 DATABASE_ENGINE=postgres
    - DJANGO=2.2 DATABASE_ENGINE=mysql
    - DJANGO=3.0 DATABASE_ENGINE=sqlite
    - DJANGO=3.0 DATABASE_ENGINE=postgres
    - DJANGO=3.0 DATABASE_ENGINE=mysql

install:
    - pip install -U setuptools zc.buildout
    - buildout versions:django=$DJANGO
    - sh -c "if [ '$DATABASE_ENGINE' = 'postgres' ];
      then
        pip install psycopg2;
        psql -c 'create database tagging;' -U postgres;
      fi"
    - sh -c "if [ '$DATABASE_ENGINE' = 'mysql' ];
      then
        pip install mysqlclient;
        mysql -e 'create database tagging CHARACTER SET utf8 COLLATE utf8_general_ci;';
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql;
      fi"
before_script:
    - ./bin/flake8 tagging
script:
    - ./bin/test-and-cover
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#django-tagging"
